/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module generatequestion_simple_39 (
    input [5:0] randomnumber,
    output reg [15:0] a,
    output reg [15:0] b,
    output reg [15:0] c
  );
  
  
  
  always @* begin
    
    case (randomnumber)
      1'h0: begin
        a = 3'h5;
        b = 3'h4;
        c = 1'h1;
      end
      1'h1: begin
        a = 4'h8;
        b = 3'h6;
        c = 2'h2;
      end
      2'h2: begin
        a = 4'h8;
        b = 3'h7;
        c = 1'h1;
      end
      2'h3: begin
        a = 2'h2;
        b = 3'h4;
        c = 4'h8;
      end
      3'h4: begin
        a = 4'h8;
        b = 3'h4;
        c = 3'h4;
      end
      3'h5: begin
        a = 2'h3;
        b = 2'h3;
        c = 1'h0;
      end
      3'h6: begin
        a = 3'h6;
        b = 2'h3;
        c = 2'h2;
      end
      3'h7: begin
        a = 1'h1;
        b = 2'h3;
        c = 2'h3;
      end
      4'h8: begin
        a = 4'h8;
        b = 2'h2;
        c = 3'h6;
      end
      4'h9: begin
        a = 1'h1;
        b = 3'h4;
        c = 3'h5;
      end
      4'ha: begin
        a = 3'h7;
        b = 2'h2;
        c = 3'h5;
      end
      4'hb: begin
        a = 2'h3;
        b = 1'h1;
        c = 2'h3;
      end
      4'hc: begin
        a = 3'h4;
        b = 2'h2;
        c = 2'h2;
      end
      4'hd: begin
        a = 2'h3;
        b = 1'h1;
        c = 2'h2;
      end
      4'he: begin
        a = 3'h6;
        b = 2'h3;
        c = 4'h9;
      end
      4'hf: begin
        a = 3'h4;
        b = 1'h1;
        c = 3'h5;
      end
      5'h10: begin
        a = 4'h8;
        b = 3'h4;
        c = 2'h2;
      end
      5'h11: begin
        a = 3'h7;
        b = 3'h5;
        c = 2'h2;
      end
      5'h12: begin
        a = 3'h5;
        b = 3'h4;
        c = 4'h9;
      end
      5'h13: begin
        a = 2'h3;
        b = 2'h3;
        c = 3'h6;
      end
      5'h14: begin
        a = 1'h1;
        b = 2'h2;
        c = 2'h3;
      end
      5'h15: begin
        a = 3'h6;
        b = 2'h3;
        c = 2'h3;
      end
      5'h16: begin
        a = 3'h6;
        b = 1'h1;
        c = 3'h5;
      end
      5'h17: begin
        a = 4'h9;
        b = 3'h5;
        c = 3'h4;
      end
      5'h18: begin
        a = 1'h1;
        b = 3'h4;
        c = 3'h4;
      end
      5'h19: begin
        a = 3'h6;
        b = 2'h2;
        c = 3'h4;
      end
      5'h1a: begin
        a = 2'h3;
        b = 3'h6;
        c = 4'h9;
      end
      5'h1b: begin
        a = 2'h3;
        b = 3'h5;
        c = 4'h8;
      end
      5'h1c: begin
        a = 2'h3;
        b = 3'h4;
        c = 3'h7;
      end
      5'h1d: begin
        a = 2'h2;
        b = 2'h3;
        c = 3'h6;
      end
      5'h1e: begin
        a = 3'h6;
        b = 3'h4;
        c = 2'h2;
      end
      5'h1f: begin
        a = 2'h3;
        b = 1'h1;
        c = 3'h4;
      end
      6'h20: begin
        a = 3'h6;
        b = 3'h5;
        c = 1'h1;
      end
      6'h21: begin
        a = 4'h8;
        b = 1'h1;
        c = 4'h8;
      end
      6'h22: begin
        a = 2'h3;
        b = 2'h2;
        c = 3'h5;
      end
      6'h23: begin
        a = 2'h2;
        b = 3'h5;
        c = 3'h7;
      end
      6'h24: begin
        a = 3'h5;
        b = 1'h1;
        c = 3'h6;
      end
      6'h25: begin
        a = 4'h9;
        b = 2'h3;
        c = 2'h3;
      end
      6'h26: begin
        a = 4'h8;
        b = 1'h1;
        c = 4'h9;
      end
      6'h27: begin
        a = 2'h3;
        b = 2'h3;
        c = 4'h9;
      end
      6'h28: begin
        a = 4'h8;
        b = 2'h2;
        c = 3'h4;
      end
      6'h29: begin
        a = 2'h2;
        b = 3'h7;
        c = 4'h9;
      end
      6'h2a: begin
        a = 2'h2;
        b = 3'h6;
        c = 4'h8;
      end
      6'h2b: begin
        a = 2'h2;
        b = 2'h3;
        c = 3'h5;
      end
      6'h2c: begin
        a = 4'h9;
        b = 3'h7;
        c = 2'h2;
      end
      6'h2d: begin
        a = 3'h5;
        b = 2'h3;
        c = 2'h2;
      end
      6'h2e: begin
        a = 3'h6;
        b = 2'h2;
        c = 2'h3;
      end
      6'h2f: begin
        a = 4'h9;
        b = 3'h4;
        c = 3'h5;
      end
      6'h30: begin
        a = 3'h4;
        b = 3'h5;
        c = 4'h9;
      end
      6'h31: begin
        a = 3'h7;
        b = 2'h2;
        c = 4'h9;
      end
      6'h32: begin
        a = 4'h9;
        b = 3'h6;
        c = 2'h3;
      end
      6'h33: begin
        a = 3'h4;
        b = 2'h2;
        c = 4'h8;
      end
      6'h34: begin
        a = 1'h1;
        b = 3'h5;
        c = 3'h6;
      end
      6'h35: begin
        a = 4'h8;
        b = 2'h3;
        c = 3'h5;
      end
      6'h36: begin
        a = 2'h3;
        b = 2'h2;
        c = 3'h6;
      end
      6'h37: begin
        a = 2'h2;
        b = 2'h2;
        c = 3'h4;
      end
      6'h38: begin
        a = 2'h2;
        b = 3'h4;
        c = 3'h6;
      end
      6'h39: begin
        a = 3'h4;
        b = 2'h2;
        c = 3'h6;
      end
      6'h3a: begin
        a = 3'h5;
        b = 2'h2;
        c = 3'h7;
      end
      6'h3b: begin
        a = 3'h5;
        b = 2'h2;
        c = 2'h3;
      end
      6'h3c: begin
        a = 3'h5;
        b = 2'h3;
        c = 4'h8;
      end
      6'h3d: begin
        a = 3'h6;
        b = 2'h2;
        c = 4'h8;
      end
      6'h3e: begin
        a = 3'h7;
        b = 2'h3;
        c = 3'h4;
      end
      6'h3f: begin
        a = 4'h9;
        b = 2'h2;
        c = 3'h7;
      end
      default: begin
        a = 1'h0;
        b = 1'h0;
        c = 1'h0;
      end
    endcase
  end
endmodule
