/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module motherposled_11 (
    input [15:0] position,
    output reg [7:0] led
  );
  
  
  
  always @* begin
    
    case (position)
      1'h0: begin
        led = 8'h01;
      end
      1'h1: begin
        led = 8'h02;
      end
      2'h2: begin
        led = 8'h04;
      end
      2'h3: begin
        led = 8'h08;
      end
      3'h4: begin
        led = 8'h10;
      end
      3'h5: begin
        led = 8'h20;
      end
      3'h6: begin
        led = 8'h40;
      end
      3'h7: begin
        led = 8'h80;
      end
      4'h8: begin
        led = 8'hff;
      end
      default: begin
        led = 8'h00;
      end
    endcase
  end
endmodule
