/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module billy_31 (
    input clk,
    input rst,
    input writeenable,
    input [15:0] writevalue,
    output reg [15:0] pos
  );
  
  
  
  reg [15:0] M_billyposition_d, M_billyposition_q = 1'h0;
  
  always @* begin
    M_billyposition_d = M_billyposition_q;
    
    if (writeenable == 1'h1) begin
      M_billyposition_d = writevalue;
    end else begin
      M_billyposition_d = M_billyposition_q;
    end
    pos = M_billyposition_q;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_billyposition_q <= 1'h0;
    end else begin
      M_billyposition_q <= M_billyposition_d;
    end
  end
  
endmodule
