/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module generatequestion_simple_37 (
    input [7:0] randomnumber,
    output reg [15:0] a,
    output reg [15:0] b,
    output reg [15:0] c,
    output reg [15:0] ans1,
    output reg [15:0] ans2
  );
  
  
  
  integer randnum;
  
  always @* begin
    randnum = randomnumber - (randomnumber / 7'h64) * 7'h64;
    
    case (randnum)
      1'h0: begin
        a = 2'h2;
        b = 2'h2;
        c = 1'h0;
        ans1 = 6'h01;
        ans2 = 6'h01;
      end
      1'h1: begin
        a = 3'h5;
        b = 3'h4;
        c = 1'h1;
        ans1 = 6'h01;
        ans2 = 6'h01;
      end
      2'h2: begin
        a = 3'h7;
        b = 3'h7;
        c = 1'h0;
        ans1 = 6'h01;
        ans2 = 6'h01;
      end
      2'h3: begin
        a = 3'h7;
        b = 3'h6;
        c = 1'h1;
        ans1 = 6'h01;
        ans2 = 6'h01;
      end
      3'h4: begin
        a = 3'h4;
        b = 1'h1;
        c = 2'h3;
        ans1 = 6'h01;
        ans2 = 6'h01;
      end
      3'h5: begin
        a = 1'h1;
        b = 3'h6;
        c = 3'h7;
        ans1 = 6'h00;
        ans2 = 6'h00;
      end
      3'h6: begin
        a = 1'h1;
        b = 1'h1;
        c = 2'h2;
        ans1 = 6'h00;
        ans2 = 6'h00;
      end
      3'h7: begin
        a = 4'h8;
        b = 3'h6;
        c = 2'h2;
        ans1 = 6'h01;
        ans2 = 6'h01;
      end
      4'h8: begin
        a = 3'h7;
        b = 1'h1;
        c = 3'h7;
        ans1 = 6'h02;
        ans2 = 6'h22;
      end
      4'h9: begin
        a = 4'h8;
        b = 3'h7;
        c = 1'h1;
        ans1 = 6'h01;
        ans2 = 6'h01;
      end
      4'ha: begin
        a = 2'h2;
        b = 3'h4;
        c = 4'h8;
        ans1 = 6'h02;
        ans2 = 6'h02;
      end
      4'hb: begin
        a = 4'h8;
        b = 3'h4;
        c = 3'h4;
        ans1 = 6'h01;
        ans2 = 6'h01;
      end
      4'hc: begin
        a = 2'h3;
        b = 2'h3;
        c = 1'h0;
        ans1 = 6'h01;
        ans2 = 6'h01;
      end
      4'hd: begin
        a = 3'h6;
        b = 2'h3;
        c = 2'h2;
        ans1 = 6'h22;
        ans2 = 6'h22;
      end
      4'he: begin
        a = 1'h1;
        b = 2'h3;
        c = 2'h3;
        ans1 = 6'h02;
        ans2 = 6'h02;
      end
      4'hf: begin
        a = 4'h8;
        b = 2'h2;
        c = 3'h6;
        ans1 = 6'h01;
        ans2 = 6'h01;
      end
      5'h10: begin
        a = 1'h1;
        b = 3'h4;
        c = 3'h5;
        ans1 = 6'h00;
        ans2 = 6'h00;
      end
      5'h11: begin
        a = 3'h7;
        b = 2'h2;
        c = 3'h5;
        ans1 = 6'h01;
        ans2 = 6'h01;
      end
      5'h12: begin
        a = 2'h3;
        b = 1'h1;
        c = 2'h3;
        ans1 = 6'h02;
        ans2 = 6'h22;
      end
      5'h13: begin
        a = 3'h4;
        b = 2'h2;
        c = 2'h2;
        ans1 = 6'h22;
        ans2 = 6'h01;
      end
      5'h14: begin
        a = 1'h1;
        b = 4'h8;
        c = 4'h9;
        ans1 = 6'h00;
        ans2 = 6'h00;
      end
      5'h15: begin
        a = 1'h1;
        b = 1'h1;
        c = 1'h0;
        ans1 = 6'h01;
        ans2 = 6'h01;
      end
      5'h16: begin
        a = 1'h1;
        b = 3'h5;
        c = 3'h5;
        ans1 = 6'h02;
        ans2 = 6'h02;
      end
      5'h17: begin
        a = 1'h1;
        b = 2'h2;
        c = 2'h2;
        ans1 = 6'h02;
        ans2 = 6'h02;
      end
      5'h18: begin
        a = 2'h2;
        b = 2'h2;
        c = 3'h4;
        ans1 = 6'h00;
        ans2 = 6'h02;
      end
      5'h19: begin
        a = 1'h1;
        b = 4'h9;
        c = 4'h9;
        ans1 = 6'h02;
        ans2 = 6'h02;
      end
      5'h1a: begin
        a = 2'h3;
        b = 1'h1;
        c = 2'h2;
        ans1 = 6'h01;
        ans2 = 6'h01;
      end
      5'h1b: begin
        a = 3'h7;
        b = 1'h1;
        c = 4'h8;
        ans1 = 6'h00;
        ans2 = 6'h00;
      end
      5'h1c: begin
        a = 2'h2;
        b = 1'h1;
        c = 2'h3;
        ans1 = 6'h00;
        ans2 = 6'h00;
      end
      5'h1d: begin
        a = 3'h6;
        b = 1'h1;
        c = 3'h7;
        ans1 = 6'h00;
        ans2 = 6'h00;
      end
      5'h1e: begin
        a = 3'h6;
        b = 2'h3;
        c = 4'h9;
        ans1 = 6'h00;
        ans2 = 6'h00;
      end
      5'h1f: begin
        a = 3'h4;
        b = 1'h1;
        c = 3'h5;
        ans1 = 6'h00;
        ans2 = 6'h00;
      end
      6'h20: begin
        a = 1'h1;
        b = 2'h3;
        c = 3'h4;
        ans1 = 6'h00;
        ans2 = 6'h00;
      end
      6'h21: begin
        a = 4'h8;
        b = 3'h4;
        c = 2'h2;
        ans1 = 6'h22;
        ans2 = 6'h22;
      end
      6'h22: begin
        a = 3'h7;
        b = 3'h5;
        c = 2'h2;
        ans1 = 6'h01;
        ans2 = 6'h01;
      end
      6'h23: begin
        a = 3'h4;
        b = 1'h1;
        c = 3'h4;
        ans1 = 6'h02;
        ans2 = 6'h22;
      end
      6'h24: begin
        a = 3'h5;
        b = 3'h4;
        c = 4'h9;
        ans1 = 6'h00;
        ans2 = 6'h00;
      end
      6'h25: begin
        a = 2'h3;
        b = 2'h3;
        c = 3'h6;
        ans1 = 6'h00;
        ans2 = 6'h00;
      end
      6'h26: begin
        a = 1'h1;
        b = 2'h2;
        c = 2'h3;
        ans1 = 6'h00;
        ans2 = 6'h00;
      end
      6'h27: begin
        a = 3'h6;
        b = 2'h3;
        c = 2'h3;
        ans1 = 6'h01;
        ans2 = 6'h01;
      end
      6'h28: begin
        a = 3'h6;
        b = 1'h1;
        c = 3'h5;
        ans1 = 6'h01;
        ans2 = 6'h01;
      end
      6'h29: begin
        a = 4'h9;
        b = 3'h5;
        c = 3'h4;
        ans1 = 6'h01;
        ans2 = 6'h01;
      end
      6'h2a: begin
        a = 1'h1;
        b = 3'h4;
        c = 3'h4;
        ans1 = 6'h02;
        ans2 = 6'h02;
      end
      6'h2b: begin
        a = 3'h5;
        b = 1'h1;
        c = 3'h4;
        ans1 = 6'h01;
        ans2 = 6'h01;
      end
      6'h2c: begin
        a = 3'h6;
        b = 2'h2;
        c = 3'h4;
        ans1 = 6'h01;
        ans2 = 6'h01;
      end
      6'h2d: begin
        a = 2'h3;
        b = 3'h6;
        c = 4'h9;
        ans1 = 6'h00;
        ans2 = 6'h00;
      end
      6'h2e: begin
        a = 2'h3;
        b = 3'h5;
        c = 4'h8;
        ans1 = 6'h00;
        ans2 = 6'h00;
      end
      6'h2f: begin
        a = 2'h3;
        b = 3'h4;
        c = 3'h7;
        ans1 = 6'h00;
        ans2 = 6'h00;
      end
      6'h30: begin
        a = 2'h2;
        b = 2'h3;
        c = 3'h6;
        ans1 = 6'h02;
        ans2 = 6'h02;
      end
      6'h31: begin
        a = 3'h6;
        b = 3'h4;
        c = 2'h2;
        ans1 = 6'h01;
        ans2 = 6'h01;
      end
      6'h32: begin
        a = 3'h4;
        b = 2'h3;
        c = 3'h7;
        ans1 = 6'h00;
        ans2 = 6'h00;
      end
      6'h33: begin
        a = 2'h3;
        b = 1'h1;
        c = 3'h4;
        ans1 = 6'h00;
        ans2 = 6'h00;
      end
      6'h34: begin
        a = 1'h1;
        b = 3'h7;
        c = 3'h7;
        ans1 = 6'h02;
        ans2 = 6'h02;
      end
      6'h35: begin
        a = 3'h6;
        b = 3'h5;
        c = 1'h1;
        ans1 = 6'h01;
        ans2 = 6'h01;
      end
      6'h36: begin
        a = 4'h8;
        b = 1'h1;
        c = 4'h8;
        ans1 = 6'h02;
        ans2 = 6'h22;
      end
      6'h37: begin
        a = 2'h3;
        b = 2'h2;
        c = 3'h5;
        ans1 = 6'h00;
        ans2 = 6'h00;
      end
      6'h38: begin
        a = 2'h2;
        b = 3'h5;
        c = 3'h7;
        ans1 = 6'h00;
        ans2 = 6'h00;
      end
      6'h39: begin
        a = 3'h5;
        b = 1'h1;
        c = 3'h6;
        ans1 = 6'h00;
        ans2 = 6'h00;
      end
      6'h3a: begin
        a = 4'h9;
        b = 2'h3;
        c = 2'h3;
        ans1 = 6'h22;
        ans2 = 6'h22;
      end
      6'h3b: begin
        a = 4'h8;
        b = 1'h1;
        c = 4'h9;
        ans1 = 6'h00;
        ans2 = 6'h00;
      end
      6'h3c: begin
        a = 2'h3;
        b = 2'h3;
        c = 4'h9;
        ans1 = 6'h02;
        ans2 = 6'h02;
      end
      6'h3d: begin
        a = 4'h8;
        b = 2'h2;
        c = 3'h4;
        ans1 = 6'h22;
        ans2 = 6'h22;
      end
      6'h3e: begin
        a = 2'h2;
        b = 3'h7;
        c = 4'h9;
        ans1 = 6'h00;
        ans2 = 6'h00;
      end
      6'h3f: begin
        a = 2'h2;
        b = 3'h6;
        c = 4'h8;
        ans1 = 6'h00;
        ans2 = 6'h00;
      end
      7'h40: begin
        a = 4'h9;
        b = 1'h1;
        c = 4'h9;
        ans1 = 6'h02;
        ans2 = 6'h22;
      end
      7'h41: begin
        a = 2'h2;
        b = 2'h3;
        c = 3'h5;
        ans1 = 6'h00;
        ans2 = 6'h00;
      end
      7'h42: begin
        a = 3'h4;
        b = 2'h3;
        c = 1'h1;
        ans1 = 6'h01;
        ans2 = 6'h01;
      end
      7'h43: begin
        a = 2'h2;
        b = 1'h1;
        c = 1'h1;
        ans1 = 6'h01;
        ans2 = 6'h01;
      end
      7'h44: begin
        a = 4'h9;
        b = 3'h7;
        c = 2'h2;
        ans1 = 6'h01;
        ans2 = 6'h01;
      end
      7'h45: begin
        a = 3'h5;
        b = 2'h3;
        c = 2'h2;
        ans1 = 6'h01;
        ans2 = 6'h01;
      end
      7'h46: begin
        a = 3'h6;
        b = 2'h2;
        c = 2'h3;
        ans1 = 6'h22;
        ans2 = 6'h22;
      end
      7'h47: begin
        a = 1'h1;
        b = 3'h6;
        c = 3'h6;
        ans1 = 6'h02;
        ans2 = 6'h02;
      end
      7'h48: begin
        a = 4'h9;
        b = 3'h4;
        c = 3'h5;
        ans1 = 6'h01;
        ans2 = 6'h01;
      end
      7'h49: begin
        a = 3'h4;
        b = 3'h5;
        c = 4'h9;
        ans1 = 6'h00;
        ans2 = 6'h00;
      end
      7'h4a: begin
        a = 4'h9;
        b = 4'h9;
        c = 1'h0;
        ans1 = 6'h01;
        ans2 = 6'h01;
      end
      7'h4b: begin
        a = 3'h7;
        b = 1'h1;
        c = 3'h6;
        ans1 = 6'h01;
        ans2 = 6'h01;
      end
      7'h4c: begin
        a = 3'h5;
        b = 1'h1;
        c = 3'h5;
        ans1 = 6'h02;
        ans2 = 6'h22;
      end
      7'h4d: begin
        a = 2'h2;
        b = 1'h1;
        c = 2'h2;
        ans1 = 6'h02;
        ans2 = 6'h22;
      end
      7'h4e: begin
        a = 3'h7;
        b = 2'h2;
        c = 4'h9;
        ans1 = 6'h00;
        ans2 = 6'h00;
      end
      7'h4f: begin
        a = 4'h9;
        b = 1'h1;
        c = 4'h8;
        ans1 = 6'h01;
        ans2 = 6'h01;
      end
      7'h50: begin
        a = 1'h1;
        b = 4'h8;
        c = 4'h8;
        ans1 = 6'h02;
        ans2 = 6'h02;
      end
      7'h51: begin
        a = 4'h9;
        b = 3'h6;
        c = 2'h3;
        ans1 = 6'h01;
        ans2 = 6'h01;
      end
      7'h52: begin
        a = 3'h4;
        b = 2'h2;
        c = 4'h8;
        ans1 = 6'h02;
        ans2 = 6'h02;
      end
      7'h53: begin
        a = 1'h1;
        b = 3'h5;
        c = 3'h6;
        ans1 = 6'h00;
        ans2 = 6'h00;
      end
      7'h54: begin
        a = 4'h8;
        b = 2'h3;
        c = 3'h5;
        ans1 = 6'h01;
        ans2 = 6'h01;
      end
      7'h55: begin
        a = 2'h3;
        b = 2'h2;
        c = 3'h6;
        ans1 = 6'h02;
        ans2 = 6'h02;
      end
      7'h56: begin
        a = 3'h6;
        b = 1'h1;
        c = 3'h6;
        ans1 = 6'h02;
        ans2 = 6'h22;
      end
      7'h57: begin
        a = 2'h2;
        b = 2'h2;
        c = 3'h4;
        ans1 = 6'h02;
        ans2 = 6'h00;
      end
      7'h58: begin
        a = 2'h2;
        b = 3'h4;
        c = 3'h6;
        ans1 = 6'h00;
        ans2 = 6'h00;
      end
      7'h59: begin
        a = 3'h4;
        b = 2'h2;
        c = 3'h6;
        ans1 = 6'h00;
        ans2 = 6'h00;
      end
      7'h5a: begin
        a = 3'h5;
        b = 2'h2;
        c = 3'h7;
        ans1 = 6'h00;
        ans2 = 6'h00;
      end
      7'h5b: begin
        a = 4'h8;
        b = 1'h1;
        c = 3'h7;
        ans1 = 6'h01;
        ans2 = 6'h01;
      end
      7'h5c: begin
        a = 3'h6;
        b = 3'h6;
        c = 1'h0;
        ans1 = 6'h01;
        ans2 = 6'h01;
      end
      7'h5d: begin
        a = 3'h4;
        b = 3'h4;
        c = 1'h0;
        ans1 = 6'h01;
        ans2 = 6'h01;
      end
      7'h5e: begin
        a = 3'h5;
        b = 2'h2;
        c = 2'h3;
        ans1 = 6'h01;
        ans2 = 6'h01;
      end
      7'h5f: begin
        a = 3'h5;
        b = 2'h3;
        c = 4'h8;
        ans1 = 6'h00;
        ans2 = 6'h00;
      end
      7'h60: begin
        a = 3'h6;
        b = 2'h2;
        c = 4'h8;
        ans1 = 6'h00;
        ans2 = 6'h00;
      end
      7'h61: begin
        a = 1'h1;
        b = 1'h1;
        c = 1'h1;
        ans1 = 6'h02;
        ans2 = 6'h22;
      end
      7'h62: begin
        a = 3'h7;
        b = 2'h3;
        c = 3'h4;
        ans1 = 6'h01;
        ans2 = 6'h01;
      end
      7'h63: begin
        a = 4'h9;
        b = 2'h2;
        c = 3'h7;
        ans1 = 6'h01;
        ans2 = 6'h01;
      end
      default: begin
        a = 1'h0;
        b = 1'h0;
        c = 1'h0;
        ans1 = 1'h0;
        ans2 = 1'h0;
      end
    endcase
  end
endmodule
