/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module operatorled_11 (
    input [5:0] opcode,
    output reg [3:0] led
  );
  
  
  
  localparam ADD = 6'h00;
  
  localparam SUB = 6'h01;
  
  localparam MUL = 6'h02;
  
  localparam DIV = 6'h22;
  
  always @* begin
    
    case (opcode)
      6'h00: begin
        led = 4'h1;
      end
      6'h01: begin
        led = 4'h2;
      end
      6'h02: begin
        led = 4'h4;
      end
      6'h22: begin
        led = 4'h8;
      end
      default: begin
        led = 4'h0;
      end
    endcase
  end
endmodule
