/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     BITS = 16
*/
module registers_31 (
    input clk,
    input rst,
    input writeenable,
    input [15:0] writevalue,
    output reg [15:0] readvalue
  );
  
  localparam BITS = 5'h10;
  
  
  reg [15:0] M_reg_d, M_reg_q = 1'h0;
  
  always @* begin
    M_reg_d = M_reg_q;
    
    readvalue = M_reg_q;
    if (writeenable == 1'h1) begin
      M_reg_d = writevalue;
    end else begin
      M_reg_d = M_reg_q;
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_reg_q <= 1'h0;
    end else begin
      M_reg_q <= M_reg_d;
    end
  end
  
endmodule
