/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mother_30 (
    input clk,
    input rst,
    input [1:0] difficulty,
    input writeenable,
    input [15:0] writevalue,
    output reg [15:0] pos
  );
  
  
  
  reg [15:0] M_motherposition_d, M_motherposition_q = 1'h0;
  reg [29:0] M_timer_d, M_timer_q = 1'h0;
  
  always @* begin
    M_timer_d = M_timer_q;
    M_motherposition_d = M_motherposition_q;
    
    
    case (difficulty)
      2'h1: begin
        M_timer_d = M_timer_q + 1'h1;
        if (M_timer_q == 29'h1dcd6500) begin
          M_timer_d = 1'h0;
          M_motherposition_d = M_motherposition_q + 1'h1;
        end
      end
      2'h2: begin
        M_timer_d = M_timer_q + 1'h1;
        if (M_timer_q == 28'ha6e49c0) begin
          M_timer_d = 1'h0;
          M_motherposition_d = M_motherposition_q + 1'h1;
        end
      end
      default: begin
        M_timer_d = 1'h0;
      end
    endcase
    if (writeenable == 1'h1) begin
      M_motherposition_d = writevalue;
      M_timer_d = M_timer_q;
    end
    pos = M_motherposition_q;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_motherposition_q <= 1'h0;
      M_timer_q <= 1'h0;
    end else begin
      M_motherposition_q <= M_motherposition_d;
      M_timer_q <= M_timer_d;
    end
  end
  
endmodule
