/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module multiply_64 (
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] mul
  );
  
  
  
  always @* begin
    mul = $signed(a[0+7-:8]) * $signed(b[0+7-:8]);
  end
endmodule
